export const prodObjOne = {
  id: "thermo",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Thermo Fisher Scientific",
  description:
    "Thermo Fisher Scientific Inc. (NYSE: TMO) is the world leader in serving science, with annual revenue exceeding $30 billion. Our Mission is to enable our customers to make the world healthier, cleaner and safer. Whether our customers are accelerating life sciences research, solving complex analytical challenges, improving patient diagnostics and therapies or increasing productivity in their laboratories, we are here to support them. Our global team of more than 80,000 colleagues delivers an unrivaled combination of innovative technologies, purchasing convenience and pharmaceutical services through our industry-leading brands, including Thermo Scientific, Applied Biosystems, Invitrogen, Fisher Scientific, Unity Lab Services and Patheon.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/thermo-logo-hd.png"),
  alt: "thermo",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website:
    "https://www.thermofisher.com/search/browse/category/pk/en/90150354/chemical+detection",
  tags: [
    "Handheld Chemical Identifaction",
    "Handheld Explosives Detection",
    "Handheld Raman Analyzers",
    "Handheld FTIRs",
    "Handheld Radiation Detection",
    "Area Monitoring",
  ],
};

export const prodObjTwo = {
  id: "honeywell",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Honeywell Safety and Productivty",
  description:
    "Honeywell Safety and Productivity Solutions (SPS) provides products, software and connected solutions that improve productivity, workplace safety and asset performance for our customers across the globe. We deliver on this promise through industry-leading mobile devices, software, cloud technology and automation solutions, the broadest range of personal protective equipment and gas detection technology, and custom-engineered sensors, switches and controls. We also manufacture and sell a broad portfolio of footwear for work, play and outdoor activities, including XTRATUF® and Muck Boot® brand footwear. SPS is a strategic business unit of Honeywell, a Fortune 100 technology company that delivers industry specific solutions that include aerospace products and services; control technologies for buildings and industry; and performance materials globally. Honeywell technologies help aircraft, buildings, manufacturing plants, supply chains, and workers become more connected to make our world smarter, safer, and more sustainable",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/honeywell-logo-hd.png"),
  alt: "honeywell",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website:
    "https://sps.honeywell.com/us/en/products/safety/gas-and-flame-detection/portables",
  tags: [
    "Portable Hazardous Gas Detection",
    "Single Gas Detectors",
    "Multi Gas Detectos",
    "Disposable Gas Detectors",
    "Area Monitoring Solutions",
  ],
};

export const prodObjThree = {
  id: "vwr",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "VWR A part of Avantor",
  description:
    "As the delivery channel of Avantor®, a Fortune 500 company, VWR provides access to mission-critical product and service solutions across life sciences and other regulated industries, including: Pharmaceutical, biotechnology, industrial, education, government, healthcare and advanced technologies. We offer an integrated, seamless purchasing experience that is optimized for the way our customers do business and supported by a strong global distribution network. Our global e-commerce platform gives you easy, convenient access to an extensive portfolio, including our own brands, as well as those from thousands of other manufacturers. Avantor is a trusted global partner to customers and suppliers in the life sciences and advanced technologies & applied materials industries. We set science in motion to create a better world.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/vwr-logo-hd.png"),
  alt: "vwr",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://us.vwr.com/store/",
  tags: [
    "QC Instruments & Consumables",
    "Vast variety of chemicals",
    "Turn Key Laboratory Setup",
    "Extensive Literature",
    "NIST Tracebility",
  ],
};
export const prodObjFour = {
  id: "onqsoft",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "OnQ Soft QLIMS",
  description:
    "OnQ Software are LIMS experts with a proven track record in delivering real benefits for laboratories around the globe. OnQ Software is Australia’s only locally owned LIMS provider. But our uniqueness isn’t in our location, it’s in our process.  From training, to implementation, servicing and updating, our team will work with you every step of the way.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/qlims-logo-hd.png"),
  alt: "onqsoft",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://www.onqsoft.com.au/best-lims-qlims/",
  tags: [
    "Laboratory Information Management System",
    "Clinical LIMS",
    "Inventory Control",
    "Instrument Integration",
    "Cloud and Perpetual Options",
    "ISO 17025, GMP, 21 CFR Part 11",
    "Software Validation",
  ],
};
export const prodObjFive = {
  id: "isystems",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "ISystems Microsoft Dynamics 365",
  description:
    "We are a leading Microsoft Dynamics partner in Central and Eastern Europe, part of the Inner Circle - the highest recognition given to only 60 out of more than 10,000 Microsoft Dynamics Partners worldwide. We know the demands of international business considering more than 495 completed implementation projects in 55+ countries. Besides the international project management methodology we use in our global deliveries, we have also gained a lot of expertise in fiscal policies in many countries in Europe, the Americas, the Middle-East and Asia.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/isystems-logo-hd.png"),
  alt: "isystems",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website:
    "https://www.isystems-group.com/solutions/pharmaceutical-life-sciences/",
  tags: [
    "Microsft Gold Partner",
    "Dynamics 365 ERP",
    "Production ERP",
    "Retail ERP",
    "Qulatiy Modules",
    "GMP, 21 CFR Part 11",
    "ERP for SMEs",
  ],
};
export const prodObjSix = {
  id: "myscada",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "MySCADA",
  description:
    "mySCADA is an independent European (Czech) company having over 20 years of experience in industrial automation. Based on this experience, mySCADA is trying to do business in a little different way. There is an extra space in between creation and long-term cooperation with our customers being able to react to special customer needs very fast and reliably. Throughout the whole mySCADA existence, we have worked with plenty of vendors (Siemens, ABB, Rockwell…) on many different projects. We are focused not only on development but also on expertise and application of industrial systems creating competitive advantages for our clients. To maintain high-quality standards, we develop and produce our products exclusively in Europe. Thank you for your interest in mySCADA products. Without your initiative, there is no such relevant improvement in our system!",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/myscada-logo-hd.png"),
  alt: "myscada",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://www.myscada.org/products/",
  tags: [
    "SCADA Systems",
    "Automation",
    "Visulaization Tool",
    "Secure Web Client",
    "Mobile App",
    "Budget Friendly",
  ],
};
export const prodObjSeven = {
  id: "perkin",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Perkin Elmer NIR Food Analyzers",
  description:
    "We provide innovative detection, imaging, informatics and service capabilities, with the knowledge and expertise needed to help customers gain earlier and more accurate insights to improve lives and the world around us. Detection, imaging, laboratory services, and informatics solutions serving the needs of scientists, clinicians, and patients. We deliver innovative solutions in the areas of Diagnostics, Life Sciences, and Applied Markets. Our solutions help scientists, lab professionals, and clinicians answer important questions that connect the impact of the environment on human health.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/perkin-logo-hd.png"),
  alt: "perkin",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://www.perkinelmer.com/category/nir-food-analyzers",
  tags: [
    "Lactose Analyzer",
    "NIR Food Analyzers",
    "Grain Analyzers",
    "Dough Analyzers",
    "In-Line Analyzers",
    "Flour Analyzers",
    "Grain Analyzers",
  ],
};
export const prodObjEight = {
  id: "gester",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Gester Testing Solutions",
  description:
    "Gester Instruments Co.,LTD is professionally engaged in production and R&D of physical properties testing equipment. With more than 20 years experience in research and development,we specialize in providing the total solutions of Toys and Baby Stuff Testing Equipment, Textiles & Garments Testing Equipment, Footwear Testing Equipment, Protective and Mask Testing Equipment. GESTER Group the subsidiaries company MKM Machinery is a specialist in designing & manufacturing of Mask Making Machine.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/gester-logo-hd.png"),
  alt: "gester",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://www.gester-instruments.com/products",
  tags: [
    "Protective & Mask Testing",
    "Textile Testing",
    "Footwear Testing",
    "Furniture Testing",
    "Environmental Testing",
    "Paper and Packaging Testing",
    "Battery Testing",
  ],
};
export const prodObjNine = {
  id: "galvano",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Galvano Scientific Intruments",
  description:
    "Since 1998, we are recognized because of our good quality instruments and best services. Galvano Scientific is a trusted name throughout the country. We have electronic engineers, software engineers, chemists, pharmacists and electronic diploma holders in our team who are key of our success. Our valued clients also guide us in improving and upgrading existing models and developing new ones. We are immensely grateful to all of them for their contribution.",
  buttonLabel: "Our Portfolio",
  imgStart: true,
  img: require("../../public/galvano-logo-hd.png"),
  alt: "galvano",
  dark: true,
  primary: true,
  darkText: true,
  noButton: false,
  website: "https://galvanoscientific.com/products/",
  tags: [
    "Made in Pakistan",
    "Tablet Disintegration Tester",
    "Tablet Dissolution Tester 8 & 14 vessels",
    "Tablet Friability Tester",
    "Column Oven for HPLC",
    "Leak Test Apparatus",
    "Multistage Stirrer 4 & 10 Position",
    "Stability Chamber",
    "Tablet Hardness Tester",
  ],
};
export const servObjOne = {
  id: "pm",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headline: "Preventive Maintenace",
  description:
    "Our team of highly trained engineers will carry out calibration & maintenance of your instruments.",
  buttonLabel: "",
  imgStart: true,
  img: require("../../public/svg-2.svg"),
  alt: "pm",
  dark: false,
  primary: false,
  darkText: false,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};

export const servObjTwo = {
  id: "sc",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Service Contracts",
  description:
    "Renewable Yearly Contracts for all your calibration & servicing needs to ensure hassle free operations",
  buttonLabel: "",
  imgStart: false,
  img: require("../../public/svg-3.svg"),
  alt: "sc",
  dark: true,
  primary: true,
  darkText: true,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};
export const servObjThree = {
  id: "md",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headline: "Method Development",
  description:
    "We can help you in development of methods per internationally accepted practices",
  buttonLabel: "",
  imgStart: true,
  img: require("../../public/svg-6.svg"),
  alt: "md",
  dark: false,
  primary: false,
  darkText: false,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};
