export const homeObjThree = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Get In Tocuh",
  headline: "Our team is always ready to assist",
  description: "Suite 2-6, Cloud Emporium, Gulberg Greens Islamabad",
  email: "info@neotek.com.pk",
  phone: "+92 304 1111 485",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: "/static/media/svg-1.aa373bca.svg",
  alt: "Contact",
  dark: true,
  primary: true,
  darkText: true,
};
