export const servObjOne = {
  id: 0,
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headline: "Service Contracts",
  description:
    "Renewable yearly contracts for all your calibration & servicing needs to ensure hassle free operations. We ensure scheduled & preventive maintenance for all your equipment and instruments with as international standards.",
  buttonLabel: "",
  imgStart: true,
  img: require("../../public/svg-3.svg"),
  alt: "pm",
  dark: false,
  primary: false,
  darkText: false,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};

export const servObjTwo = {
  id: 1,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Method Development",
  description:
    "We can help you in development of methods per internationally accepted practices. We work closely with you throughout the various stages of development i.e. feasibility, development and validation to ensure best outcomes.",
  buttonLabel: "",
  imgStart: false,
  img: require("../../public/svg-4.svg"),
  alt: "sc",
  dark: true,
  primary: true,
  darkText: true,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};
export const servObjThree = {
  id: 2,
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headline: "Preventive Maintenace",
  description:
    "Need help with one of your equipment or instruments? We are happy to help. Our team can run diagnostics on the apparatus in question and inform you of the condition at which point you can choose to proceed or not according to your internal policies.",
  buttonLabel: "",
  imgStart: true,
  img: require("../../public/svg-10.svg"),
  alt: "md",
  dark: false,
  primary: false,
  darkText: false,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};
export const servObjFour = {
  id: 3,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Consultancy Services",
  description:
    "Our panel of experts who have decades of experience in their respective disciplines. We leverage these expertise to provide you insights as a service that is well coordinated and results in maximum benefits for your organization in the shortest timeframe possible.",
  buttonLabel: "",
  imgStart: false,
  img: require("../../public/svg-12.svg"),
  alt: "sc",
  dark: true,
  primary: true,
  darkText: true,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};
export const servObjFive = {
  id: 4,
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headline: "Annual Supply Contracts",
  description:
    "Through our extensive range of partners, we enable supply chain departments to cut down on the number of vendors they have to rely on to fulfill their demands. We provide a one stop shop for a vast variety of products including chemicals, reagent and consumables for our clients to source thereby improving their departmental efficiency as well as speeding up fulfillment.",
  buttonLabel: "",
  imgStart: true,
  img: require("../../public/svg-11.svg"),
  alt: "md",
  dark: false,
  primary: false,
  darkText: false,
  noButton: true,
  website: "https://galvanoscientific.com/products/",
  tags: [],
};

export const Data = [
  {
    id: 0,
    href: "/services",
    aria: "Annual Supply Contracts",
    alt: "asc",
    src: require("../../public/svg-11.svg"),
  },
  {
    id: 1,
    href: "/services",
    aria: "Consultancy Services",
    alt: "cs",
    src: require("../../public/svg-12.svg"),
  },
  {
    id: 2,
    href: "/services",
    aria: "Service Contracts",
    alt: "sc",
    src: require("../../public/svg-3.svg"),
  },
  {
    id: 3,
    href: "/services",
    aria: "Method Development",
    alt: "md",
    src: require("../../public/svg-4.svg"),
  },
  {
    id: 4,
    href: "/services",
    aria: "Preventive Maintenace",
    alt: "pm",
    src: require("../../public/svg-10.svg"),
  },
];
